// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykhhwyfdfrwncbbdhgod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlraGh3eWZkZnJ3bmNiYmRoZ29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODcxOTcsImV4cCI6MjA2MDY2MzE5N30.D3WGdTFHrZgIQC3HmiMJ7AOKITLqblnIELChz6bAx9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);